# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ticso/git/mb_mqttbridge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ticso/git/mb_mqttbridge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ticso/git/mb_mqttbridge/CMakeFiles /home/ticso/git/mb_mqttbridge//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ticso/git/mb_mqttbridge/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ticso/git/mb_mqttbridge/CMakeFiles /home/ticso/git/mb_mqttbridge//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ticso/git/mb_mqttbridge/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mb_mqttbrdige

# Build rule for target.
mb_mqttbrdige: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mb_mqttbrdige
.PHONY : mb_mqttbrdige

# fast build rule for target.
mb_mqttbrdige/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/build
.PHONY : mb_mqttbrdige/fast

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/mqtt.o: src/mqtt.cc.o
.PHONY : src/mqtt.o

# target to build an object file
src/mqtt.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/mqtt.cc.o
.PHONY : src/mqtt.cc.o

src/mqtt.i: src/mqtt.cc.i
.PHONY : src/mqtt.i

# target to preprocess a source file
src/mqtt.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/mqtt.cc.i
.PHONY : src/mqtt.cc.i

src/mqtt.s: src/mqtt.cc.s
.PHONY : src/mqtt.s

# target to generate assembly for a file
src/mqtt.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/mqtt.cc.s
.PHONY : src/mqtt.cc.s

src/vendor_bwct.o: src/vendor_bwct.cc.o
.PHONY : src/vendor_bwct.o

# target to build an object file
src/vendor_bwct.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_bwct.cc.o
.PHONY : src/vendor_bwct.cc.o

src/vendor_bwct.i: src/vendor_bwct.cc.i
.PHONY : src/vendor_bwct.i

# target to preprocess a source file
src/vendor_bwct.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_bwct.cc.i
.PHONY : src/vendor_bwct.cc.i

src/vendor_bwct.s: src/vendor_bwct.cc.s
.PHONY : src/vendor_bwct.s

# target to generate assembly for a file
src/vendor_bwct.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_bwct.cc.s
.PHONY : src/vendor_bwct.cc.s

src/vendor_eastron.o: src/vendor_eastron.cc.o
.PHONY : src/vendor_eastron.o

# target to build an object file
src/vendor_eastron.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_eastron.cc.o
.PHONY : src/vendor_eastron.cc.o

src/vendor_eastron.i: src/vendor_eastron.cc.i
.PHONY : src/vendor_eastron.i

# target to preprocess a source file
src/vendor_eastron.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_eastron.cc.i
.PHONY : src/vendor_eastron.cc.i

src/vendor_eastron.s: src/vendor_eastron.cc.s
.PHONY : src/vendor_eastron.s

# target to generate assembly for a file
src/vendor_eastron.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_eastron.cc.s
.PHONY : src/vendor_eastron.cc.s

src/vendor_epever.o: src/vendor_epever.cc.o
.PHONY : src/vendor_epever.o

# target to build an object file
src/vendor_epever.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_epever.cc.o
.PHONY : src/vendor_epever.cc.o

src/vendor_epever.i: src/vendor_epever.cc.i
.PHONY : src/vendor_epever.i

# target to preprocess a source file
src/vendor_epever.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_epever.cc.i
.PHONY : src/vendor_epever.cc.i

src/vendor_epever.s: src/vendor_epever.cc.s
.PHONY : src/vendor_epever.s

# target to generate assembly for a file
src/vendor_epever.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_epever.cc.s
.PHONY : src/vendor_epever.cc.s

src/vendor_mru.o: src/vendor_mru.cc.o
.PHONY : src/vendor_mru.o

# target to build an object file
src/vendor_mru.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_mru.cc.o
.PHONY : src/vendor_mru.cc.o

src/vendor_mru.i: src/vendor_mru.cc.i
.PHONY : src/vendor_mru.i

# target to preprocess a source file
src/vendor_mru.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_mru.cc.i
.PHONY : src/vendor_mru.cc.i

src/vendor_mru.s: src/vendor_mru.cc.s
.PHONY : src/vendor_mru.s

# target to generate assembly for a file
src/vendor_mru.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_mru.cc.s
.PHONY : src/vendor_mru.cc.s

src/vendor_trucki.o: src/vendor_trucki.cc.o
.PHONY : src/vendor_trucki.o

# target to build an object file
src/vendor_trucki.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_trucki.cc.o
.PHONY : src/vendor_trucki.cc.o

src/vendor_trucki.i: src/vendor_trucki.cc.i
.PHONY : src/vendor_trucki.i

# target to preprocess a source file
src/vendor_trucki.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_trucki.cc.i
.PHONY : src/vendor_trucki.cc.i

src/vendor_trucki.s: src/vendor_trucki.cc.s
.PHONY : src/vendor_trucki.s

# target to generate assembly for a file
src/vendor_trucki.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_trucki.cc.s
.PHONY : src/vendor_trucki.cc.s

src/vendor_zgej.o: src/vendor_zgej.cc.o
.PHONY : src/vendor_zgej.o

# target to build an object file
src/vendor_zgej.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_zgej.cc.o
.PHONY : src/vendor_zgej.cc.o

src/vendor_zgej.i: src/vendor_zgej.cc.i
.PHONY : src/vendor_zgej.i

# target to preprocess a source file
src/vendor_zgej.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_zgej.cc.i
.PHONY : src/vendor_zgej.cc.i

src/vendor_zgej.s: src/vendor_zgej.cc.s
.PHONY : src/vendor_zgej.s

# target to generate assembly for a file
src/vendor_zgej.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mb_mqttbrdige.dir/build.make CMakeFiles/mb_mqttbrdige.dir/src/vendor_zgej.cc.s
.PHONY : src/vendor_zgej.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mb_mqttbrdige"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mqtt.o"
	@echo "... src/mqtt.i"
	@echo "... src/mqtt.s"
	@echo "... src/vendor_bwct.o"
	@echo "... src/vendor_bwct.i"
	@echo "... src/vendor_bwct.s"
	@echo "... src/vendor_eastron.o"
	@echo "... src/vendor_eastron.i"
	@echo "... src/vendor_eastron.s"
	@echo "... src/vendor_epever.o"
	@echo "... src/vendor_epever.i"
	@echo "... src/vendor_epever.s"
	@echo "... src/vendor_mru.o"
	@echo "... src/vendor_mru.i"
	@echo "... src/vendor_mru.s"
	@echo "... src/vendor_trucki.o"
	@echo "... src/vendor_trucki.i"
	@echo "... src/vendor_trucki.s"
	@echo "... src/vendor_zgej.o"
	@echo "... src/vendor_zgej.i"
	@echo "... src/vendor_zgej.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

